name: Push Docker Image

on:
  push:
    branches:
      - main # 또는 배포하려는 브랜치

env:
  DOCKER_REGISTRY: heewoni # Docker Hub 사용시
  IMAGE_NAME: redis # 이미지 이름
  IMAGE_TAG: latest # 이미지 태그
  DOCKERFILE_PATH: ./app # 빌드를 원하는 폴더 경로
  CONTAINER_NAME: redis # 컨테이너 이름

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Docker Image Build
      - name: Build
        run: |-
          pwd
          docker build -t ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          docker push ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      -
        name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} 
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
              docker pull ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
              docker stop ${{ env.CONTAINER_NAME }}
              docker rm ${{ env.CONTAINER_NAME }}
              docker rmi $(docker images -f "dangling=true" -q)
              docker run --env-file .env -d --name ${{ env.CONTAINER_NAME }} -p 8080:8080 ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}